version: '2'

services:
  server:
    image: 'jetbrains/teamcity-server'
    volumes:
      - '/opt/teamcity/data:/data/teamcity_server/datadir'
      - '/opt/teamcity/log:/opt/teamcity/logs'
    ports:
      - 8111:8111
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=server:8111
      - AGENT_NAME="rbenv builder"
      - DATABASE_URL=postgresql://prayermate:dev@postgres:5432/prayermate_test?encoding=UTF8&pool=5&timeout=5000
    volumes:
      - 'teamcity_agent_rbenv_conf:/data/teamcity_agent/conf'
      - '/opt/teamcity/platform/system:/data/teamcity_agent/platform/system'
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.13
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=prayermate
      - POSTGRES_USER=prayermate
      - POSTGRES_PASSWORD=dev
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
volumes:
  teamcity_agent_rbenv_conf: